# Generated by Django 3.2.7 on 2021-09-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="task",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
